language: java

sudo: required

env:
  - ARCH=x64

before_script:
  - echo "deb http://download.tizen.org/tools/latest-release/Ubuntu_12.04/ /" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install gbs -y --force-yes

script:
  - "bash -ex .travis-ci.sh"
